version: '3'
services:
  # container 1
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /Documents/DockerWorkdir/node_modules
      - .:/Documents/DockerWorkdir/
  # container 2
  tests:
     build:
       context: .
       dockerfile: Dockerfile.dev
     volumes:
       - /Documents/DockerWorkdir/node_modules
       - .:/Documents/DockerWorkdir/
     command: ["npm", "run", test"]

